import os
'''删除.txt文件'''
cur_path = os.path.dirname(os.path.realpath(__file__))
path = os.path.join(cur_path, "autogenerated")
print(path)
for maindir,subdir,file_name_list in os.walk(path):  
    for filename in file_name_list:  
        if(filename.endswith(".py") or filename.endswith(".json")):  
            os.remove(maindir+"\\"+filename)  
        else: 
            print("None")